name: Upload_WeTransfer

on:
  workflow_dispatch:
   inputs:
    File_URL:
        description: 'File_URL'
        required: true
        default: 'https://github.com/ShihabZzz/Releases/releases/download/146.0/lineage-18.1-20211028-UNOFFICIAL-markw.zip'
    File_NAME:
        description: 'File_NAME'
        required: true
        default: 'lineage-18.1-20211028-UNOFFICIAL-markw.zip'
        
jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget p7zip-full p7zip-rar
       
       - name: Download File
         run: |
            sudo mkdir Downloads
            cd $GITHUB_WORKSPACE/Downloads
            echo "-----------开始下载 : ${{ github.event.inputs.File_NAME }} -----------"
            sudo wget ${{ github.event.inputs.File_URL }}
            echo "--------------------------------------------"
            sudo ls
            echo "--------------------------------------------"
            
        - name: File Md5
          run: |
            echo "-----------正在设置权限-----------"
            sudo chmod 777 -R $GITHUB_WORKSPACE/Downloads
            echo "-----------权限设置完成-----------"
            cd $GITHUB_WORKSPACE/Downloads
            echo -e "\n正在输出: ${{ github.event.inputs.File_NAME }} 的Md5"
            sudo md5sum ${{ github.event.inputs.File_NAME }}
            echo "-----------以上为 ${{ github.event.inputs.File_NAME }} 的Md5-----------"
            

        - name: Upload File to WeTransfer
          run: |
            curl -sL https://git.io/file-transfer | sh
            ./transfer wet ./Downloads/${{ github.event.inputs.File_NAME }}